"""add source_audio_key to tasks

Revision ID: 8b52d2548eb5
Revises: 7d1c41c552e1
Create Date: 2026-07-13 19:46:38.446912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b52d2548eb5'
down_revision: Union[str, None] = '7d1c41c552e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('source_audio_key', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'source_audio_key')
    # ### end Alembic commands ###
