"""generalize payment provider fields, add paystack support

Revision ID: cafcc6b831f3
Revises: 8b52d2548eb5
Create Date: 2026-07-14 05:35:20.907400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cafcc6b831f3'
down_revision: Union[str, None] = '8b52d2548eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider', sa.String(length=20), nullable=False))
    op.add_column('payments', sa.Column('provider_reference', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('checkout_url', sa.String(length=1024), nullable=True))
    op.drop_constraint('payments_opay_order_id_key', 'payments', type_='unique')
    op.create_unique_constraint(None, 'payments', ['provider_reference'])
    op.drop_column('payments', 'opay_checkout_url')
    op.drop_column('payments', 'opay_order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('opay_order_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('opay_checkout_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='unique')
    op.create_unique_constraint('payments_opay_order_id_key', 'payments', ['opay_order_id'])
    op.drop_column('payments', 'checkout_url')
    op.drop_column('payments', 'provider_reference')
    op.drop_column('payments', 'provider')
    # ### end Alembic commands ###
